name: fix-sh-config
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - aenum==3.1.17
    - annotated-types==0.7.0
    - certifi==2026.4.22
    - charset-normalizer==3.4.7
    - click==8.3.3
    - dataclasses-json==0.6.7
    - idna==3.14
    - marshmallow==3.26.2
    - mypy_extensions==1.1.0
    - numpy==2.4.4
    - oauthlib==3.3.1
    - packaging==26.2
    - pillow==12.2.0
    - pydantic==2.13.4
    - pydantic-settings==2.14.1
    - pydantic_core==2.46.4
    - pyproj==3.7.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.2
    - requests==2.33.1
    - requests-oauthlib==2.0.0
    - sentinelhub==3.11.5
    - shapely==2.1.2
    - six==1.17.0
    - tifffile==2026.5.2
    - tomli==2.4.1
    - tomli_w==1.2.0
    - tqdm==4.67.3
    - typing-inspect==0.9.0
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - urllib3==2.7.0
    - utm==0.8.1
